theme: minima
title: test
description: test description
baseurl: /website
plugins: ['jekyll/scholar']
scholar:
  source: /_bibliography
  bibliography: ikim.bib
  repository: /files/publications
  style: chicago-fullnote-bibliography
  group_by: year
  group_order: descending
  bibliography_template: bib
